### ISSUE TITLE
docs: make agent.yml details more consistent 

### ISSUE THREAD

**Issue by Stephenitis** [ClusterHQ/flocker#2142]
https://docs.clusterhq.com/en/1.6.1/config/configuring-nodes-storage.html

1. Notation for control service and version keys is slightly different from datset examples (quotations around key names and no quotations in dataset object examples)
a fuller example of a agent yaml should be displayed here as it is not immediately apparent that user needs to add *dataset* object in there.

OLD
```
"version": 1
"control-service":
   "hostname": "${CONTROL_NODE}"
   "port": 4524
```

I suggest showing the user this fuller example on the above page.
```
version" 1
control-service:
   hostname: "${CONTROL_NODE}"
   port: 4524

# The dataset key below selects and configures a dataset backend (see below: aws/openstack/etc).
# All nodes will be configured to use only one backend

dataset:
    backend: "aws"
    region: "<region slug; for example, us-west-1>"
    zone: "<availability zone slug; for example, us-west-1a>"
    access_key_id: "<AWS API key identifier>"
    secret_access_key: "<Matching AWS API key>"
```

Alternatively make all supported backend agent.ymls include more domain specific control service configuration. (allow user to download example ymls from link)
see: https://docs.clusterhq.com/en/1.6.1/config/aws-configuration.html
```
"version": 1
"control-service":
   "hostname": "${CONTROL_NODE}"
   "port": 4524
# backed dataset specific information below
```
