### ISSUE TITLE
Flocker on Webserver using EBS Storage Backend

### ISSUE THREAD

**Issue by slowflyer** [ClusterHQ/flocker#2803]
Followed the latest docs to manually install Flocker on my webserver. (https://docs.clusterhq.com/en/latest/docker-integration/manual-install.html)

After installation when trying to run: 

docker run -v apples:/data --volume-driver flocker busybox sh -c "echo hello > /data/file.txt"

I receive:

docker: Error response from daemon: Timed out waiting for dataset to mount..

My agent.yml looks like:

```
"version": 1
"control-service":
   "hostname": "master.mydomain.net"
   "port": 4524

# The dataset key below selects and configures a dataset backend (see below: aws/openstack/etc).
# All nodes will be configured to use only one backend

dataset:
   backend: "aws"
   region: "eu-central-1"
   zone: "eu-central-1a"
   access_key_id: "__________ZVSCZM2Q"
   secret_access_key: "IbQ/wtSCGvdM_______________dwT1cApS1"
```
flocker-dataset-agent.log:

{"count": 4, "function": "_discover_raw_state", "task_uuid": "c561aeef-dfc0-4739-bcef-693987e9d518", "timestamp": 1464613835.866328, "message_type": "flocker:node:agents:blockdevice:list_volumes", "task_level": [2, 2, 2, 2, 2, 2, 2, 2]}
{"count": 4, "task_uuid": "c561aeef-dfc0-4739-bcef-693987e9d518", "task_level": [2, 2, 2, 2, 2, 2, 2, 3, 1], "action_type": "flocker:node:agents:blockdevice:aws", "timestamp": 1464613835.866618, "operation": ["compute_instance_id", [], {}], "action_status": "started"}
{"exception": "flocker.node.agents.blockdevice.UnknownInstanceID", "task_level": [2, 2, 2, 2, 2, 2, 2, 3, 2], "action_type": "flocker:node:agents:blockdevice:aws", "reason": "Could not find valid instance ID for <flocker.node.agents.ebs.EBSBlockDeviceAPI object at 0x7fb65a021690>", "timestamp": 1464614487.301161, "task_uuid": "c561aeef-dfc0-4739-bcef-693987e9d518", "action_status": "failed"}
{"exception": "flocker.node.agents.blockdevice.UnknownInstanceID", "task_level": [2, 2, 2, 2, 2, 2, 2, 4], "action_type": "flocker:agent:discovery", "reason": "Could not find valid instance ID for <flocker.node.agents.ebs.EBSBlockDeviceAPI object at 0x7fb65a021690>", "timestamp": 1464614487.302578, "task_uuid": "c561aeef-dfc0-4739-bcef-693987e9d518", "action_status": "failed"}
{"exception": "flocker.node.agents.blockdevice.UnknownInstanceID", "reason": "Could not find valid instance ID for <flocker.node.agents.ebs.EBSBlockDeviceAPI object at 0x7fb65a021690>", "timestamp": 1464614487.303283, "traceback": "Traceback: <class 'flocker.node.agents.blockdevice.UnknownInstanceID'>: Could not find valid instance ID for <flocker.node.agents.ebs.EBSBlockDeviceAPI object at 0x7fb65a021690>\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_logging.py:102:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:534:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:592:output\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py:529:output_CONVERGE\n--- <exception caught here> ---\n/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1798:discover_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1345:_count_calls\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1743:_discover_raw_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:2023:compute_instance_id\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/ebs.py:561:_run_with_logging\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/ebs.py:1024:compute_instance_id\n", "message_type": "eliot:traceback", "task_uuid": "c561aeef-dfc0-4739-bcef-693987e9d518", "task_level": [2, 2, 2, 2, 2, 2, 3]}

There are no volumes listed on the AWS console.

No idea, how to move forward, after 2 days spend on this.
