### ISSUE TITLE
flocker openstack backend connect to V1 API

### ISSUE THREAD

**Issue by rupamroy** [ClusterHQ/flocker#2870]
Here is agent.yml
```yml
"version": 1
"control-service":
   "hostname": "flocker-master.cloud.corp.dig.com"
   "port": 4524


dataset:
   backend: "openstack"
   verify_peer: false
   region: "dtss1"
   auth_plugin: "password"
   username: "royr016"
   tenant_name: "RA-Mesosphere-Sandbox"
   password: "myPassword"
   auth_url: "http://iaas-api.starwave.com:5000/v2.0"
```

The error that i get is  when i start flocker-dataset-service is attached here. But at the crux of the error it is 
```
CinderAPIVersionDetectionFailure(endpoint_errors=[EndpointNotFound(u'publicURL endpoint for volumev2 service in dtss1 region not found',), EndpointNotFound(u'publicURL endpoint for volume service in dtss1 region not found',)])\n", "message_type": "twisted:log", "task_level": [1]}
Jul 21 20:
```

Does this mean that there is no volume URL endpoint for both V1 and V2 API versions available for the region ? 

How can i resolve this issue?
